name: dart_injektor
description: This is a lightweight dependency injection package in Dart language that provides the ability to register and resolve dependencies.

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
