name: Dart Tests and Analysis with Code Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Dart Design Patterns Analysis and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Pub Dependencies
        run: dart pub get

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze Project Source
        run: dart analyze

      - name: Run tests with coverage
        run: |
          dart test --coverage=coverage
          genhtml coverage/lcov.info --output-directory coverage/report
        env:
          CI: true

      - name: Upload Code Coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage/report/index.html
